language: generic 

sudo: required
services:
    - docker
    
before_install:
    - docker build -t gsanti23/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true gsanti23/docker-react npm run test
    
