language: generic 

sudo: required
services:
    - docker
    
before_install:
    - docker build -t Giuliano94/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true Giuliano94/docker-react npm run test
    
